version: '3.8'

services:
  sensevoice:
    build: .
    container_name: sensevoice-rknn2
    restart: unless-stopped
    volumes:
      - ./audio:/opt/sensevoice/audio
      - ./models:/opt/sensevoice/models
      - /dev:/dev
      # Mount host RKNN runtime library if available
      - /usr/lib:/usr/lib:ro
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PYTHONUNBUFFERED=1
      - SPEECH_SCALE=0.5
    ports:
      - "8081:8080"
    command: ["python3", "./sensevoice_rknn.py", "--audio_file", "/opt/sensevoice/audio/test.wav"]

volumes:
  audio_data:
  models_data: 